language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: HtYcimvs7NZnAB5lOIzVEIWfs2bKvH4tpkNfX9BFbbvU2yUuYWy5z54dTiWfu1y6ObRPJ4XXu9YK/OdmxMmBqXgmgx+ynEjC2/HoTyRuYWA0gCT5OIDlQkMeixMkMy2SM6xZo7fZeuVhJJAgwZSzpSaZ4/TxbWAgUJa8whExAzcwmh3/hYtKqpoksPRC2rDKwE6ZqRWnhwd1jcg4KNEQUQcCVxBOPTDqkOE25yySaI91Vl77/GkSPBIotsLqYaQXnDqm3tys8/a6VZUNbG/omqcosVnQOMH8D9m7kd27lniJpWbsjbgSVBwgm1e0xMrw6Tnx5vWtqHqo+G8WIetQ3AXN8nYPoszrQyYtVkyT9pueb9bI/NTj2HSy6Kc8LP9GPLncJGDI2eKhDE/FHA/2dqMLD4llMWdyupBMcgD82W5Mv7uzug4oIqFMW+8Mro9YiGO8Qx+lccwHZDZ0CK600f3AZl0ZKBacFRgd3CHnLNE1hIpZXKTXOhz4WGP9G53eU10Oz4ScbNjY1hKM2bWPKzcOFBdYmSzQ4/JczmclJPpoVsdPLzmLKawc9y8DykoCMoZyKEKjb/d5rMPxDqRvFTkEt80O8SgvzyNBUdSxfWZ9DahQNkOPj3fV56TCGhvtKEe1D/u4XVzSe+u6LYppatFeuRqAsSdFnn1ah2HlzhE=
  app: streamline-capstone
  on:
    repo: thinkful-ei17/Tricia-Jeff-Node-Capstone
